### ISSUE TITLE
response_body is never a string

### ISSUE THREAD

**Issue by jridgway** [grosser/easy_esi#2]
To get this working, I had to remove replace following lines:

```
return if @do_not_replace_esi or not response_body.kind_of?(String)
self.response_body = EasyEsi.replace_includes(response_body) do |data|
```

with:

```
return if @do_not_replace_esi
self.response_body = EasyEsi.replace_includes(response_body.first) do |data|
```

I'm using Rails 3.0.10.

**Comment by grosser** [comment]
which rails version are you using ?

**Comment by jridgway** [comment]
I'm using Rails 3.0.10 with RefineryCMS. BTW, my solution was just the first hack I got working. I look forward to what you come up with.

**Comment by grosser** [comment]
if response is a file thiss would fail, can you `raise response_body.class.to_s`, so this can be used as test.
Can you write a failing test for the test-suite, I am not able to get a failure with the current code

**Comment by grosser** [comment]
i think this should be fixed now
