### ISSUE TITLE
class_inheritable_attribute is deprecated

### ISSUE THREAD

**Issue by promisedlandt** [grosser/easy_esi#3]
Using Rails 3.1.1, I get the following deprecation warnings:

DEPRECATION WARNING: class_inheritable_attribute is deprecated, please use class_attribute method instead. Notice their behavior are slightly different, so refer to class_attribute documentation first. (called from <top (required)> at /home/blablabla/config/application.rb:8)

I think the offender are in line 62 and following:

```
class ActionController::Base
  class_inheritable_accessor :esi_enabled

  def self.enable_esi
    self.esi_enabled = true
    after_filter :render_esi
  end
```

**Comment by grosser** [comment]
are you able to turn this issue into a pull request ? :)

**Comment by promisedlandt** [comment]
Sadly, I can't even get the tests to run on RVM with Ruby 1.9.2p290, even when explicitly requiring test-unit. 
If you do not have any time, I'll try to check it out during the weekend.
